image: openjdk:8-jdk

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH:"0"

stages:
  -build
  -test
  -code-analysis

before_script:
  -chmod +x gradlew

buildJob:
  stage: build
  script:
  - ./gradlew build

testJob:
  stage: testscript:
  - ./gradlew check
  - ./gradlew codeCoverageReport
  artifacts:
    paths:
      -build/reports/jacoco

sonarcloud-check:
  stage: code-analysis
  dependencies:
    - testJob
  Image: sonasource/sonar-scanner-cli:latest
  cache:
    key:"${CI_JOB_NAME}
    paths:
      - .sonar/cache
    script:
      -sonar-scanner
      -apk add bash
      -bash <(Curl -s https://codecov.io/bash) -t
    only:
      - merge_requests
      - master
      - develop
     
